[tools]
buf = "latest"
go = "latest"
node = "22"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
"npm:pnpm" = "latest"
"npm:ccusage" = "latest"
"npm:dev3000" = "latest"
"npm:eas-cli" = "latest"
"npm:vercel" = "latest"
"npm:@fission-ai/openspec" = "latest"
terraform = "latest"
uv = "latest"
"npm:yarn" = "latest"
bun = "latest"
rust = "latest"
"cargo:wrkflw" = "latest"
aws-cli = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
